baseURL = 'https://post-self.ink/'
languageCode = 'en-us'
title = 'Post-Self'
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    # author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = '2020—­2022'
    customCSS = ['/css/toledot.css']

[markup.goldmark.renderer]
    unsafe = true
